### PR TITLE
fix charging mode random disconnect

### PR DESCRIPTION
**Pull request by ZjemCiKolege**
I tested no disconnect :+1:

### CODE REVIEW

**Comment by MarcKe** [comment]
685c actually means mtp, but doesn't usb charging mean that nothing is enabled?
Im wondering if we should maybe use an unused number.

**Comment by MarcKe** [comment]
685b mass_storage
685e mass_storage,adb
685c mtp 
6860 mtp,adb
6862 rndis,dm
6863 rndis
6864 rndis,adb & rndis,acm,dm
6865 ptp
6866 ptp,adb

**Comment by ZjemCiKolege** [comment]
It works but they are trying to connect to the computer :+1:

**Comment by ZjemCiKolege** [comment]
Maybe this is issue cm? i try with new number :+1:

**Comment by MarcKe** [comment]
Ye, as I said. Just try a number that is not used, like 6867. It should work

**Pull request closed without merging**
